[features]
seeds = false
[programs.localnet]
ggoldca = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --exit"

[test]
startup_wait = 20_000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# USDH mint
[[test.validator.clone]]
address = "USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX"

# USDC mint
[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

# Hubble protocol token mint
[[test.validator.clone]]
address = "HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6"

# Orca
[[test.validator.clone]]
address = "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE"

# USDH-USDC whirlpool
[[test.validator.clone]]
address = "Fvtf8VCjnkqbETA6KtyHYqHm26ut6w184Jqm4MQjPvv7"

# USDH whirlpool vault
[[test.validator.clone]]
address = "4WuB7EYM6N42583EnFkWPusbWUZB5X9ESErUU5gQ5dra"

# USDC whirlpool vault
[[test.validator.clone]]
address = "GHQjuFa7XY4GXPYHZ1cWtkqcCqxMQ6eNt4op7dhaVnSd"

# Hubble protocol token whirlpool vault
[[test.validator.clone]]
address = "FtyAqoebZvqv71Y8eq13rXrj5CXbpT5nSaRgndSaWMC7"

# Orca whirlpool vault
[[test.validator.clone]]
address = "Gun69u86yfheQpdB2DfJhKQqZ8xs9DudjFQypQucFYEi"

# whirlpool program
[[test.validator.clone]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"

# USDC_ata for DrrB1 with 10^12 lamports
[[test.validator.account]]
address = "CL6TVscze5qrzhb9vJjydDWxj8dB2kj5YUAK5j1s2cAW"
filename = "./tests/accounts/CL6TVscze5qrzhb9vJjydDWxj8dB2kj5YUAK5j1s2cAW.json"

# USDH_ata for DrrB1 with 10^12 lamports
[[test.validator.account]]
address = "51C35yS12BEvDmcLAV2DDt3oAcQxP5dQUpnihE2ZABMo"
filename = "./tests/accounts/51C35yS12BEvDmcLAV2DDt3oAcQxP5dQUpnihE2ZABMo.json"
