[features]
seeds = false
[programs.localnet]
ggoldca = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --exit"

[test]
startup_wait = 10_000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# USDH mint
[[test.validator.clone]]
address = "USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX"

# USDC mint
[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

## USDH-USDC whirlpool
#[[test.validator.clone]]
#address = "Fvtf8VCjnkqbETA6KtyHYqHm26ut6w184Jqm4MQjPvv7"
#
## whirlpool program
#[[test.validator.clone]]
#address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
